Fixes "Column 'id' in where clause is ambiguous" error while building…
anomalylabs/multiple-field_type pull request #22
Opened 2016-10-06 15:01 UTC by aliselcuk

In lookup mode, when there are no entries, ValueTableBuilder fails with `Column 'id' in where clause is ambiguous...` error

2016-10-06 15:41 UTC, RyanThompson commented on src/Table/ValueTableBuilder.php
> +            $query->whereIn($query->getModel()->getTable() . '.id', $uploaded ?: [0]);
This should be the same as `$table` above right? Can you update to use that instead of the additional logic? Thanks!

2016-10-06 15:42 UTC, RyanThompson requested changes
I think that line can be simplified - take a look and update if you would please!

2016-10-06 16:32 UTC, aliselcuk commented on src/Table/ValueTableBuilder.php
> +            $query->whereIn($query->getModel()->getTable() . '.id', $uploaded ?: [0]);
Tried $table, but since it refers to the pivot table it didn't work.

2016-10-10 09:43 UTC, huglester commented
@RyanThompson how this can improved?
In products module:

$query->getModel()->getTable() =>  products_categories

while 
$table => products_products_categories

2016-11-02 17:53 UTC, closed without merging

2016-11-03 05:17 UTC, huglester commented
@aliselcuk it is not the case anymore?

2016-11-03 05:42 UTC, aliselcuk commented
@huglester this is fixed by @RyanThompson already, see the original file